import { v4 as uuidv4 } from 'uuid';
const CssTool = [
  {
    id: uuidv4(),
    image: '/images/css-file-format.png',
    title: 'CSS Minify Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/minify-css',
    desc: 'Generate CSS Minify with our generator tool.',
  },
  {
    id: uuidv4(),
    image: '/images/css-file-format.png',
    title: 'CSS Formatter Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/css-formatter',
    desc: 'Generate CSS Formatter with our generator tool.',
  },
  {
    id: uuidv4(),
    image: '/images/card-icon-21.png',
    title: 'CSS Gradient Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/gradient',
    desc: 'Generate CSS gradient with our CSS generator tool.',
  },
  {
    id: uuidv4(),
    image: '/images/css-file-format.png',
    title: 'CSS Transform Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/transform-gen',
    desc: 'Generate CSS Transform with our generator tool.',
  },
  {
    id: uuidv4(),
    image: '/images/css-file-format.png',
    title: 'CSS Background Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/background-gen',
    desc: 'Generate CSS Background with our generator tool.',
  },
  {
    id: uuidv4(),
    image: '/images/css-file-format.png',
    title: 'CSS Opacity Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/opacity-gen',
    desc: 'Generate CSS Opacity with our generator tool.',
  },
  {
    id: uuidv4(),
    image: '/images/css-file-format.png',
    title: 'CSS List Style Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/list-style-gen',
    desc: 'Generate CSS List Style with our generator tool.',
  },
  {
    id: uuidv4(),
    image: '/images/css-file-format.png',
    title: 'CSS Cursor Generator',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/cursor',
    desc: 'Generate CSS Cursor with our generator tool.',
  },
  {
    id: uuidv4(),
    image: '/images/css-file-format.png',
    title: 'CSS Tab Size',
    category: 'CSS Tools',
    categorysty: 'dec',
    type: '',
    link: '/css-tool/tab-size-gen',
    desc: 'generate Tab sizes',
  },
];
export default CssTool;
