import { v4 as uuidv4 } from 'uuid';
const HtmlTool = [
  {
    id: uuidv4(),
    image: '/images/html-file.png',
    title: 'HTML Minify Generator',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-minify',
    desc: 'Generate HTML Minify with our generator tool.',
  },
  {
    id: uuidv4(),
    image: '/images/html-file.png',
    title: 'HTML Formatter',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-formatter',
    desc: 'HTML Formatter with our generator tool.',
  },
  {
    id: uuidv4(),
    image: '/images/html-file.png',
    title: 'HTML Form Builder',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-form-builder',
    desc: 'Build accessible, responsive HTML forms with ARIA attributes, validation, and all input types. No code required.',
  },
  {
    id: uuidv4(),
    image: '/images/html-file.png',
    title: 'HTML Embed Builder & Preview',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-embed-builder',
    desc: 'Generate safe HTML embed code for iframes, video, audio, images, and quotes. Includes sandboxing, privacy options, and lazy loading.',
  },
  {
    id: uuidv4(),
    image: '/images/html-file.png',
    title: 'HTML Element Builder',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-element-builder',
    desc: 'Generate HTML elements for text formatting, links, details, meter, and progress bars. Create semantic HTML code with live preview. 12 element types in one tool.',
  },
  {
    id: uuidv4(),
    image: '/images/html-file.png',
    title: 'HTML Validator & Linter',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-validator',
    desc: 'Validate HTML5 code with W3C standards. Check for syntax errors, missing tags, accessibility issues, and browser compatibility. Real-time validation and detailed error reports.',
  },
  {
    id: uuidv4(),
    image: '/images/html-file.png',
    title: 'HTML Accessibility Auditor',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-accessibility-checker',
    desc: 'Check HTML for WCAG 2.1 AA compliance. Analyze color contrast, ARIA attributes, keyboard navigation, and screen reader compatibility. Get accessibility score and recommendations.',
  },
  {
    id: uuidv4(),
    image: '/images/html-file.png',
    title: 'HTML Security Scanner',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-security-scanner',
    desc: 'Scan HTML for security vulnerabilities. Detect XSS risks, CSP issues, insecure resources, and missing security headers. OWASP Top 10 compliance checking.',
  },
  {
    id: uuidv4(),
    image: '/images/html-file.png',
    title: 'HTML SEO Analyzer',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-seo-analyzer',
    desc: 'Analyze HTML for SEO optimization. Check meta tags, structured data, heading hierarchy, image alt text, and Core Web Vitals. Get SEO score with actionable recommendations.',
  },
  {
    id: uuidv4(),
    image: '/images/html-file.png',
    title: 'HTML Performance Analyzer',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-performance-analyzer',
    desc: 'Analyze HTML performance and Core Web Vitals. Detect render-blocking resources, oversized images, missing lazy loading, and optimization opportunities. Performance score with suggestions.',
  },
  {
    id: uuidv4(),
    image: '/images/html-file.png',
    title: 'HTML Email Template Builder',
    category: 'HTML Tools',
    categorysty: 'dec',
    type: '',
    link: '/html/html-email-builder',
    desc: 'Build HTML email templates with email-safe code. Generate table-based layouts, inline CSS, and test compatibility across Gmail, Outlook, and other email clients. Dark mode support included.',
  },
];
export default HtmlTool;
