import { v4 as uuidv4 } from 'uuid';

const webTools = [
  {
    id: uuidv4(),
    image: '/images/keyword selection.svg',
    title: 'Website Screenshot',
    category: 'Web Tools',
    categorysty: 'dec',
    type: 'website-screenshot',
    link: '/web-tools/website-screenshot',
    desc: 'Take screenshots of any website URL and download as PNG or PDF. Free online website screenshot tool with full-page capture and customizable options.',
  },
  {
    id: uuidv4(),
    image: '/images/keyword selection.svg',
    title: 'Website Speed Test',
    category: 'Web Tools',
    categorysty: 'dec',
    type: 'website-speed-test',
    link: '/web-tools/website-speed-test',
    desc: 'Test your website speed and performance. Get Core Web Vitals scores, page load times, and performance recommendations. Free website speed test tool.',
  },
  {
    id: uuidv4(),
    image: '/images/keyword selection.svg',
    title: 'SSL Certificate Checker',
    category: 'Web Tools',
    categorysty: 'dec',
    type: 'ssl-checker',
    link: '/web-tools/ssl-checker',
    desc: 'Check SSL certificate validity, expiration date, issuer, and security. Free SSL certificate checker tool to verify your website SSL certificate status.',
  },
  {
    id: uuidv4(),
    image: '/images/keyword selection.svg',
    title: 'DNS Lookup',
    category: 'Web Tools',
    categorysty: 'dec',
    type: 'dns-lookup',
    link: '/web-tools/dns-lookup',
    desc: 'Lookup DNS records for any domain. Check A, AAAA, MX, TXT, CNAME, NS records. Free DNS lookup tool with real-time DNS resolution and propagation check.',
  },
  {
    id: uuidv4(),
    image: '/images/keyword selection.svg',
    title: 'HTTP Header Checker',
    category: 'Web Tools',
    categorysty: 'dec',
    type: 'http-header-checker',
    link: '/web-tools/http-header-checker',
    desc: 'Check HTTP response headers for any website. Analyze security headers, redirects, and server information. Free HTTP header checker and analyzer tool.',
  },
  {
    id: uuidv4(),
    image: '/images/keyword selection.svg',
    title: 'Website Uptime Monitor',
    category: 'Web Tools',
    categorysty: 'dec',
    type: 'uptime-monitor',
    link: '/web-tools/uptime-monitor',
    desc: 'Monitor website uptime and availability. Check if your website is online, track response times, and get uptime statistics. Free website uptime checker.',
  },
  {
    id: uuidv4(),
    image: '/images/keyword selection.svg',
    title: 'Website Accessibility Checker',
    category: 'Web Tools',
    categorysty: 'dec',
    type: 'accessibility-checker',
    link: '/web-tools/accessibility-checker',
    desc: 'Check website accessibility and WCAG compliance. Find accessibility issues, test ARIA labels, and analyze color contrast. Free accessibility checker tool.',
  },
  {
    id: uuidv4(),
    image: '/images/keyword selection.svg',
    title: 'Broken Link Checker',
    category: 'Web Tools',
    categorysty: 'dec',
    type: 'broken-link-checker',
    link: '/web-tools/broken-link-checker',
    desc: 'Find broken links on your website. Scan entire website for dead links, 404 errors, and redirect issues. Free broken link checker and validator tool.',
  },
  {
    id: uuidv4(),
    image: '/images/keyword selection.svg',
    title: 'Website Metadata Extractor',
    category: 'Web Tools',
    categorysty: 'dec',
    type: 'metadata-extractor',
    link: '/web-tools/metadata-extractor',
    desc: 'Extract and analyze website metadata, meta tags, Open Graph tags, and structured data. Free website metadata checker and SEO tag analyzer tool.',
  },
  {
    id: uuidv4(),
    image: '/images/keyword selection.svg',
    title: 'Website Comparison Tool',
    category: 'Web Tools',
    categorysty: 'dec',
    type: 'website-comparison',
    link: '/web-tools/website-comparison',
    desc: 'Compare two websites side-by-side. Analyze performance, SEO, accessibility, and get visual comparisons. Free website comparison and analyzer tool.',
  },
  {
    id: uuidv4(),
    image: '/images/keyword selection.svg',
    title: 'URL Redirect Checker',
    category: 'Web Tools',
    categorysty: 'dec',
    type: 'redirect-checker',
    link: '/web-tools/redirect-checker',
    desc: 'Check URL redirects and follow redirect chains. Detect 301, 302 redirects, find final destination, and check for redirect loops. Free redirect checker tool.',
  },
  {
    id: uuidv4(),
    image: '/images/keyword selection.svg',
    title: 'Website Traffic Checker',
    category: 'Web Tools',
    categorysty: 'dec',
    type: 'traffic-checker',
    link: '/web-tools/traffic-checker',
    desc: 'Check and estimate website traffic, visitor statistics, and popularity metrics. Analyze website traffic trends, page views, and engagement metrics. Free website traffic checker tool.',
  },
];

export default webTools;

